dist: bionic
language: go
go:
- 1.14.x

git:
  depth: false

cache:
  directories:
    - "$HOME/vcpkg"
    - "$HOME/Downloads"

matrix:
  include:
    - os: linux
      env:
        - VCPKG_TRIPLET="x64-linux"
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh -disableMetrics"
        - SYSTEM_TRIPLET="linux"
        - PREFERRED_ARCHIVE_EXTENSION="tar.gz"
        - LIBOFFKV_CMAKE_FLAGS=""
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
    - os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="brew install gcc@7"
        - OSX_ENABLE_GCC="CC=gcc-7 && CXX=g++-7"
        - OSX_ENABLE_CLANG="CC=clang && CXX=clang++"
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh -disableMetrics"
        - SYSTEM_TRIPLET="darwin"
        - PREFERRED_ARCHIVE_EXTENSION="zip"
        - LIBOFFKV_CMAKE_FLAGS=""
    # - os: windows
    #   env:
    #     - VCPKG_TRIPLET=x64-windows
    #     - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.bat"
    #     - SYSTEM_TRIPLET=windows
    #     - PREFERRED_ARCHIVE_EXTENSION=zip

before_install:
  - eval "$MATRIX_EVAL"
  - eval "$OSX_ENABLE_GCC"

before_script:
  - set +x
  - curl -sL https://github.com/offscale/kv-travis-scripts/archive/master.zip | jar xv
  - mv kv-travis-scripts-master "$HOME/scripts"
  - pushd "$HOME/scripts"
  - chmod +x *.bash
  #- ./prepare_vcpkg.bash "$HOME/vcpkg/" "$VCPKG_BOOT_EVAL"
  - ./bootstrap_etcd.bash "$SYSTEM_TRIPLET" "$PREFERRED_ARCHIVE_EXTENSION"
  - ./bootstrap_consul.bash "$SYSTEM_TRIPLET"
  - ./bootstrap_zk.bash
  - popd
  # - cp -r "$TRAVIS_BUILD_DIR/vcpkg/ports" "$HOME/vcpkg/"
  #- pushd "$HOME/vcpkg"
  #- travis_wait 30 ./vcpkg upgrade --no-dry-run
  #- eval "$OSX_ENABLE_CLANG"
  #- travis_wait 25 ./vcpkg install gtest || "$HOME/scripts/export_vcpkg_logs.bash"
  #- travis_wait 34 ./vcpkg install ppconsul || "$HOME/scripts/export_vcpkg_logs.bash"
  #- travis_wait 25 ./vcpkg install zkpp || "$HOME/scripts/export_vcpkg_logs.bash"
  #- travis_wait 35 ./vcpkg install offscale-libetcd-cpp || "$HOME/scripts/export_vcpkg_logs.bash"
  #- ls -lR
  #- rm -rf buildtrees

script:
  - go test
  #- mkdir "$TRAVIS_BUILD_DIR/cmake-build-debug" && pushd "$_"
  #- cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" -DBUILD_TESTS=ON "${LIBOFFKV_CMAKE_FLAGS}" ..
  #- cmake --build .
  #- ctest --verbose

after_failure:
  - "$HOME/scripts/send_status_message.bash"
